services:

  keycloak-db:
    image: postgres:15-alpine
    container_name: keycloak_db
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=KeycloakPass123
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    depends_on:
      - keycloak-db
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: KeycloakPass123
    volumes:
      - ./keycloak_import/mobilizon-realm.json:/opt/keycloak/data/import/mobilizon-realm.json

    command:
      - start-dev
      - --verbose
      - --import-realm
    ports:
      - "8080:8080"
    restart: unless-stopped

  mobilizon-db:
    build: .
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mobilizon
      - POSTGRES_USER=mobilizon
      - POSTGRES_PASSWORD=MobilizonPass123
    volumes:
      - mobilizon_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  mobilizon:

    image: framasoft/mobilizon:latest
    container_name: mobilizon_app
    depends_on:
      - mobilizon-db
    environment:
      # Database connection settings
      MOBILIZON_DATABASE_HOST: mobilizon-db
      MOBILIZON_DATABASE_DBNAME: mobilizon
      MOBILIZON_DATABASE_USERNAME: mobilizon
      MOBILIZON_DATABASE_PASSWORD: MobilizonPass123
      MOBILIZON_DATABASE_PORT: 5432

      # Instance settings
      MOBILIZON_INSTANCE_HOST: localhost
      MOBILIZON_INSTANCE_PORT: 4000
      MOBILIZON_INSTANCE_NAME: "My Mobilizon Instance"
      MOBILIZON_INSTANCE_EMAIL: "noreply@example.com"
      MOBILIZON_INSTANCE_REGISTRATIONS_OPEN: "true"
      
      MOBILIZON_INSTANCE_LOCAL_ONLY: "true"
      MOBILIZON_FEDERATION_ENABLED: "false"

      # Replace these secrets with secure random values for production
      MOBILIZON_INSTANCE_SECRET_KEY_BASE: "CHANGE_ME_TO_50_CHAR_RANDOMCHANGE_ME_TO_50_CHAR_RANDOM"
      MOBILIZON_INSTANCE_SECRET_KEY: "CHANGE_ME_TO_50_CHAR_RANDOMxCHANGE_ME_TO_50_CHAR_RANDOM"

    volumes:
      - ./mobilizon_config/config.exs:/etc/mobilizon/config.exs:ro

    ports:
      - "4000:4000"
    restart: unless-stopped

volumes:
  mobilizon_db_data:
  keycloak_db_data:
